name: Tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  unit_tests:
    name: Unit Tests
    if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        ruby:
          - jruby-9.2.13.0
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - ruby-head
        allow_failures:
          - false
#        include:
#          - os: ubuntu
#            ruby: ruby-head
#            gemfile: gemfiles/contracts_16_0.gemfile
#            allow_failures: true
    env:
      ALLOW_FAILURES: "${{ matrix.allow_failures }}"
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rspec || $ALLOW_FAILURES
